# Generated by Django 6.0.7 on 2026-07-30 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('customer_address', models.CharField(max_length=255, verbose_name='住所')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('status', models.CharField(choices=[('awaiting_payment', '支払待ち'), ('paid', '入金済み'), ('shipped', '発送済み')], default='awaiting_payment', max_length=20, verbose_name='ステータス')),
                ('total_price', models.PositiveIntegerField(verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='単価')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
